-- MySQL Script generated by MySQL Workbench
-- Mon Aug 29 11:40:13 2022
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`books` (
  `bookid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bookid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`books_borrowed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`books_borrowed` (
  `books_borrowedid` INT NOT NULL,
  `bookid` INT NOT NULL,
  `borrowerid` INT NOT NULL,
  `date_borrowed` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `date_returned` DATE NULL,
  INDEX `bookid_idx` (`bookid` ASC),
  INDEX `borrowerid_idx` (`borrowerid` ASC),
  PRIMARY KEY (`books_borrowedid`),
  CONSTRAINT `bookid`
    FOREIGN KEY (`bookid`)
    REFERENCES `new_schema1`.`books` (`bookid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `borrowerid`
    FOREIGN KEY (`borrowerid`)
    REFERENCES `new_schema1`.`borrowers` (`borrowerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`borrowers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`borrowers` (
  `borrowerid` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phonenumber` INT NOT NULL,
  `address1` VARCHAR(45) NOT NULL,
  `address2` VARCHAR(45) NULL,
  `suburb` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `postcode` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`borrowerid`),
  UNIQUE INDEX `password_UNIQUE` (`password` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
